development:
  adapter: mysql
  database: wishlist
  host: localhost
  username: root
  password: confidential

test:
  adapter: mysql
  database: wishlist_test
  host: localhost
  username: root
  password: 

production:
  adapter: mysql
  database: wishlist
  host: localhost
  username: root
  password: 
